from __future__ import annotations

import json
from pathlib import Path

import pytest

from game_llm_translator.models import TextEntry, TranslationResult
from game_llm_translator.rpg_maker import (
    _parse_path,
    _set_json_value,
    _walk_json,
    apply_rpg_maker,
    detect_rpg_maker,
    extract_rpg_maker,
)
from game_llm_translator.rpg_maker_common import _detect_json_indent


# ---------------------------------------------------------------------------
# _parse_path
# ---------------------------------------------------------------------------

def test_parse_path_simple_key():
    assert _parse_path("$.name") == ["name"]


def test_parse_path_nested_keys():
    assert _parse_path("$.actors.name") == ["actors", "name"]


def test_parse_path_array_index():
    assert _parse_path("$[0].name") == [0, "name"]


def test_parse_path_nested_array():
    assert _parse_path("$[1].list[2].parameters[0]") == [1, "list", 2, "parameters", 0]


def test_parse_path_only_root():
    assert _parse_path("$") == []


# ---------------------------------------------------------------------------
# _set_json_value
# ---------------------------------------------------------------------------

def test_set_json_value_simple():
    data = {"name": "old"}
    _set_json_value(data, "$.name", "new")
    assert data["name"] == "new"


def test_set_json_value_list():
    data = [{"name": "old"}]
    _set_json_value(data, "$[0].name", "new")
    assert data[0]["name"] == "new"


def test_set_json_value_deep():
    data = [None, {"list": [None, None, {"parameters": ["orig"]}]}]
    _set_json_value(data, "$[1].list[2].parameters[0]", "translated")
    assert data[1]["list"][2]["parameters"][0] == "translated"


# ---------------------------------------------------------------------------
# detect_rpg_maker
# ---------------------------------------------------------------------------

def test_detect_rpg_maker_mv_mz_via_data(tmp_path):
    data_dir = tmp_path / "data"
    data_dir.mkdir()
    (data_dir / "Actors.json").write_text("[]")
    assert detect_rpg_maker(tmp_path) == "mv-mz"


def test_detect_rpg_maker_mv(tmp_path):
    data_dir = tmp_path / "www" / "data"
    data_dir.mkdir(parents=True)
    js_dir = tmp_path / "www" / "js"
    js_dir.mkdir()
    (js_dir / "rpg_core.js").write_text("")
    assert detect_rpg_maker(tmp_path) == "mv"


def test_detect_rpg_maker_mz(tmp_path):
    data_dir = tmp_path / "data"
    data_dir.mkdir()
    js_dir = tmp_path / "js"
    js_dir.mkdir()
    (js_dir / "rmmz_core.js").write_text("")
    assert detect_rpg_maker(tmp_path) == "mz"


def test_detect_rpg_maker_www_data(tmp_path):
    www = tmp_path / "www" / "data"
    www.mkdir(parents=True)
    js = tmp_path / "www" / "js"
    js.mkdir()
    (js / "rpg_core.js").write_text("")
    assert detect_rpg_maker(tmp_path) == "mv"


def test_detect_rpg_maker_unknown(tmp_path):
    assert detect_rpg_maker(tmp_path) is None


# ---------------------------------------------------------------------------
# extract_rpg_maker
# ---------------------------------------------------------------------------

ACTORS_JSON = json.dumps([
    None,
    {"id": 1, "name": "Harold", "nickname": "The Sword", "profile": "A brave warrior.", "description": "", "note": ""},
])

SKILLS_JSON = json.dumps([
    None,
    {
        "id": 1,
        "name": "Attack",
        "description": "A normal attack.",
        "message1": "\\V[1] attacks!",
        "message2": "",
        "note": "",
    },
])

SYSTEM_JSON = json.dumps({
    "armorTypes": ["", "Cloth", "Mail"],
    "elements": ["", "Fire", "Water"],
    "skillTypes": ["", "Magic"],
    "weaponTypes": ["", "Sword"],
    "equipTypes": ["", "Weapon"],
    "switches": ["", "switch1"],
    "variables": ["", "var1"],
    "gameTitle": "Test Game",
    "currencyUnit": "Gold",
    "title1Name": "TitleAsset",
    "battleBgm": {"name": "Battle1", "volume": 90, "pitch": 100, "pan": 0},
    "sounds": [{"name": "Cursor2", "volume": 90, "pitch": 100, "pan": 0}],
    "terms": {
        "basic": ["Level", "HP"],
        "commands": ["Fight", "Escape"],
        "params": ["Max HP", "Attack"],
        "messages": {"saveMessage": "Save to which file?"},
    },
    "locale": "en_US",
})


def _make_rpg_game(tmp_path: Path, files: dict[str, str]) -> Path:
    data_dir = tmp_path / "data"
    data_dir.mkdir()
    for name, content in files.items():
        (data_dir / name).write_text(content, encoding="utf-8")
    return tmp_path


def _make_plugins_js(tmp_path: Path, plugins: list[dict]) -> Path:
    """Create www/js/plugins.js for testing."""
    js_dir = tmp_path / "www" / "js"
    js_dir.mkdir(parents=True)
    (tmp_path / "www" / "data").mkdir(parents=True, exist_ok=True)
    content = "// Generated by Translator++.\nvar $plugins =\n" + json.dumps(plugins, ensure_ascii=False, indent=2) + ";\n"
    (js_dir / "plugins.js").write_text(content, encoding="utf-8")
    return tmp_path


def test_extract_plugins_js_save_menu_strings(tmp_path):
    """plugins.js parameter values like 'ロード' (Load) must be extracted (T++ parity)."""
    plugins = [
        {
            "name": "YEP_SaveCore",
            "status": True,
            "description": "Save core",
            "parameters": {
                "Load Command": "ロード",
                "Save Command": "セーブ",
                "Delete Command": "削除",
                "Select Help": "ファイルを選択",
                "Playtime": "タイム：",
                "Internal Setting": "true",  # filtered out by _is_translatable_ui_text
            },
        },
        {
            "name": "DisabledPlugin",
            "status": False,
            "parameters": {"Should Not Extract": "スキップ"},
        },
    ]
    _make_plugins_js(tmp_path, plugins)
    entries = extract_rpg_maker(tmp_path)
    sources = [e.source for e in entries]
    contexts = [e.context for e in entries]
    assert "ロード" in sources
    assert "セーブ" in sources
    assert "削除" in sources
    assert "ファイルを選択" in sources
    assert "タイム：" in sources
    assert "true" not in sources  # filtered
    assert "スキップ" not in sources  # disabled plugin skipped
    assert any(ctx == "rpg_maker_plugin_param_YEP_SaveCore" for ctx in contexts)


def test_apply_plugins_js_writes_in_place(tmp_path):
    """Apply pipeline writes plugins.js back to source path (in-place), not output_dir."""
    plugins = [{
        "name": "YEP_SaveCore",
        "status": True,
        "parameters": {"Load Command": "ロード", "Save Command": "セーブ"},
    }]
    _make_plugins_js(tmp_path, plugins)
    plugins_path = tmp_path / "www" / "js" / "plugins.js"

    results = [
        TranslationResult(
            file=plugins_path,
            key="$[0].parameters['Load Command']",
            source="ロード",
            target="Tải game",
            context="rpg_maker_plugin_param_YEP_SaveCore",
        ),
        TranslationResult(
            file=plugins_path,
            key="$[0].parameters['Save Command']",
            source="セーブ",
            target="Lưu game",
            context="rpg_maker_plugin_param_YEP_SaveCore",
        ),
    ]
    out_dir = tmp_path / "out"
    apply_rpg_maker(results, out_dir)

    rewritten = plugins_path.read_text(encoding="utf-8")
    assert '"Tải game"' in rewritten
    assert '"Lưu game"' in rewritten
    assert rewritten.lstrip().startswith("//") or "var $plugins" in rewritten
    # Should not be written under output_dir
    assert not (out_dir / "plugins.js").exists()


def test_extract_rpg_maker_actors(tmp_path):
    _make_rpg_game(tmp_path, {"Actors.json": ACTORS_JSON})
    entries = extract_rpg_maker(tmp_path)
    sources = [e.source for e in entries]
    assert "Harold" in sources
    assert "The Sword" in sources
    assert "A brave warrior." in sources


def test_extract_rpg_maker_skills(tmp_path):
    _make_rpg_game(tmp_path, {"Skills.json": SKILLS_JSON})
    entries = extract_rpg_maker(tmp_path)
    sources = [e.source for e in entries]
    assert "Attack" in sources
    assert "A normal attack." in sources
    assert "\\V[1] attacks!" in sources


def test_extract_rpg_maker_system_arrays(tmp_path):
    _make_rpg_game(tmp_path, {"System.json": SYSTEM_JSON})
    entries = extract_rpg_maker(tmp_path)
    sources = [e.source for e in entries]
    # armorTypes, elements, skillTypes, weaponTypes, equipTypes should be extracted
    assert "Cloth" in sources
    assert "Fire" in sources
    assert "Magic" in sources
    assert "Sword" in sources
    assert "Test Game" in sources
    assert "Gold" in sources
    assert "Level" in sources
    assert "Fight" in sources
    assert "Max HP" in sources
    assert "Save to which file?" in sources
    # switches/variables now extracted (T++ parity); assets remain excluded
    assert "switch1" in sources
    assert "var1" in sources
    assert "TitleAsset" not in sources
    assert "Battle1" not in sources
    assert "Cursor2" not in sources


def test_extract_rpg_maker_skips_asset_names(tmp_path):
    map_data = json.dumps({
        "displayName": "Town Entrance",
        "battleback1Name": "Road3",
        "battleback2Name": "Town1",
        "parallaxName": "Clouds",
        "bgm": {"name": "Town 1", "volume": 90, "pitch": 100, "pan": 0},
        "events": [
            None,
            {
                "id": 1,
                "name": "EV001",
                "pages": [
                    {
                        "image": {"characterName": "Actor1", "characterIndex": 0},
                        "list": [
                            {"code": 231, "parameters": [1, "PictureAsset"]},
                            {"code": 241, "parameters": [{"name": "Battle1", "volume": 90, "pitch": 100, "pan": 0}]},
                            {"code": 250, "parameters": [{"name": "Open1", "volume": 90, "pitch": 100, "pan": 0}]},
                            {"code": 401, "parameters": ["Welcome!"]},
                        ],
                    }
                ],
            },
        ],
    })
    _make_rpg_game(tmp_path, {"Map001.json": map_data})
    entries = extract_rpg_maker(tmp_path)
    sources = [e.source for e in entries]
    assert "Town Entrance" in sources
    assert "Welcome!" in sources
    assert "Town 1" not in sources
    assert "Actor1" not in sources
    assert "Road3" not in sources
    assert "Town1" not in sources
    assert "Clouds" not in sources
    assert "PictureAsset" not in sources
    assert "Battle1" not in sources
    assert "Open1" not in sources


def test_extract_rpg_maker_event_choices(tmp_path):
    map_data = json.dumps({
        "events": [
            None,
            {
                "id": 1,
                "pages": [
                    {
                        "list": [
                            {"code": 102, "parameters": [["Yes", "No"], 0, 0, 2, 0]},
                            {"code": 402, "parameters": [0, "Yes"]},
                        ]
                    }
                ],
            },
        ],
    })
    _make_rpg_game(tmp_path, {"Map001.json": map_data})
    entries = extract_rpg_maker(tmp_path)
    assert [entry.source for entry in entries] == ["Yes", "No"]
    assert [entry.key for entry in entries] == [
        "$.events[1].pages[0].list[0].parameters[0][0]",
        "$.events[1].pages[0].list[0].parameters[0][1]",
    ]


def test_extract_rpg_maker_extracts_plugin_and_script_commands(tmp_path):
    """T++ parity: scripts (355/655), plugin commands (356/357), comments (108/408) all extracted."""
    map_data = json.dumps({
        "events": [
            None,
            {
                "id": 1,
                "pages": [
                    {
                        "list": [
                            {"code": 355, "parameters": ["$gameMessage.add('Script text')"]},
                            {"code": 655, "parameters": ["continued script text"]},
                            {"code": 356, "parameters": ["Plugin Command Text"]},
                            {"code": 357, "parameters": ["PluginName", "command", "Display Text"]},
                            {"code": 108, "parameters": ["Comment line 1"]},
                            {"code": 408, "parameters": ["Comment line 2"]},
                            {"code": 401, "parameters": ["Visible dialogue"]},
                        ]
                    }
                ],
            },
        ],
    })
    _make_rpg_game(tmp_path, {"Map001.json": map_data})
    entries = extract_rpg_maker(tmp_path)
    sources = [entry.source for entry in entries]
    contexts = {entry.context for entry in entries}
    assert "Visible dialogue" in sources
    assert "Plugin Command Text" in sources
    assert "Display Text" in sources
    assert "$gameMessage.add('Script text')\ncontinued script text" in sources
    assert "Comment line 1\nComment line 2" in sources
    assert {"rpg_maker_event_text", "rpg_maker_plugin_command", "rpg_maker_script", "rpg_maker_comment"} <= contexts


def test_extract_rpg_maker_www_data(tmp_path):
    data_dir = tmp_path / "www" / "data"
    data_dir.mkdir(parents=True)
    (data_dir / "Actors.json").write_text(ACTORS_JSON, encoding="utf-8")
    entries = extract_rpg_maker(tmp_path)
    assert any(entry.source == "Harold" for entry in entries)


def test_extract_rpg_maker_skips_editor_name_files(tmp_path):
    # Animations + Tilesets now extract `name` (T++ parity); only verify Tilesets `tilesetNames` (asset list) is skipped
    tilesets = json.dumps([None, {"id": 1, "name": "外", "tilesetNames": ["World_A1"]}])
    _make_rpg_game(tmp_path, {"Tilesets.json": tilesets})
    entries = extract_rpg_maker(tmp_path)
    sources = [e.source for e in entries]
    assert "外" in sources
    assert "World_A1" not in sources  # asset filenames stay out


def test_extract_rpg_maker_map_infos_names(tmp_path):
    map_infos = json.dumps([None, {"id": 1, "name": "森の入口"}, {"id": 2, "name": "城の中"}])
    _make_rpg_game(tmp_path, {"MapInfos.json": map_infos})
    entries = extract_rpg_maker(tmp_path)
    assert {(e.source, e.context) for e in entries} == {
        ("森の入口", "rpg_maker_map_name"),
        ("城の中", "rpg_maker_map_name"),
    }


def test_extract_rpg_maker_troops_top_level_names(tmp_path):
    troops = json.dumps([
        None,
        {
            "id": 1,
            "name": "ボス戦",
            "members": [{"enemyId": 1, "x": 0, "y": 0}],
            "pages": [{"conditions": {}, "list": [{"code": 0, "indent": 0, "parameters": []}]}],
        },
    ])
    _make_rpg_game(tmp_path, {"Troops.json": troops})
    entries = extract_rpg_maker(tmp_path)
    assert any(e.source == "ボス戦" and e.context == "rpg_maker_troops_name" for e in entries)


def test_extract_rpg_maker_event_text(tmp_path):
    map_data = json.dumps([
        None,
        {
            "id": 1,
            "events": [
                None,
                {
                    "id": 1,
                    "pages": [
                        {
                            "list": [
                                {"code": 401, "parameters": ["Hello, world!"]},
                                {"code": 401, "parameters": ["Another line."]},
                            ]
                        }
                    ],
                },
            ],
        },
    ])
    _make_rpg_game(tmp_path, {"Map001.json": map_data})
    entries = extract_rpg_maker(tmp_path)
    sources = [e.source for e in entries]
    assert "Hello, world!" in sources
    assert "Another line." in sources


def test_extract_rpg_maker_invalid_json_skipped(tmp_path):
    data_dir = tmp_path / "data"
    data_dir.mkdir()
    (data_dir / "Bad.json").write_text("NOT JSON", encoding="utf-8")
    (data_dir / "Actors.json").write_text(ACTORS_JSON, encoding="utf-8")
    entries = extract_rpg_maker(tmp_path)
    assert any(e.source == "Harold" for e in entries)


# ---------------------------------------------------------------------------
# apply_rpg_maker
# ---------------------------------------------------------------------------

def test_apply_rpg_maker_basic(tmp_path):
    src = tmp_path / "data" / "Actors.json"
    src.parent.mkdir(parents=True)
    src.write_text(ACTORS_JSON, encoding="utf-8")
    out_dir = tmp_path / "out"

    results = [
        TranslationResult(file=src, key="$[1].name", source="Harold", target="Ha-rôn"),
        TranslationResult(file=src, key="$[1].nickname", source="The Sword", target="Kiếm Sĩ"),
    ]
    apply_rpg_maker(results, out_dir)

    out_file = out_dir / "Actors.json"
    assert out_file.exists()
    data = json.loads(out_file.read_text(encoding="utf-8"))
    assert data[1]["name"] == "Ha-rôn"
    assert data[1]["nickname"] == "Kiếm Sĩ"


def test_apply_rpg_maker_creates_output_dir(tmp_path):
    src = tmp_path / "data" / "Actors.json"
    src.parent.mkdir(parents=True)
    src.write_text(ACTORS_JSON, encoding="utf-8")
    out_dir = tmp_path / "deep" / "nested" / "out"

    results = [TranslationResult(file=src, key="$[1].name", source="Harold", target="Ha-rôn")]
    apply_rpg_maker(results, out_dir)
    assert (out_dir / "Actors.json").exists()


def test_apply_rpg_maker_multiple_files(tmp_path):
    actors_src = tmp_path / "data" / "Actors.json"
    skills_src = tmp_path / "data" / "Skills.json"
    actors_src.parent.mkdir(parents=True)
    actors_src.write_text(ACTORS_JSON, encoding="utf-8")
    skills_src.write_text(SKILLS_JSON, encoding="utf-8")
    out_dir = tmp_path / "out"

    results = [
        TranslationResult(file=actors_src, key="$[1].name", source="Harold", target="Ha-rôn"),
        TranslationResult(file=skills_src, key="$[1].name", source="Attack", target="Tấn công"),
    ]
    apply_rpg_maker(results, out_dir)
    actors_out = json.loads((out_dir / "Actors.json").read_text(encoding="utf-8"))
    skills_out = json.loads((out_dir / "Skills.json").read_text(encoding="utf-8"))
    assert actors_out[1]["name"] == "Ha-rôn"
    assert skills_out[1]["name"] == "Tấn công"


def test_apply_rpg_maker_preserves_nested_data_paths(tmp_path):
    src = tmp_path / "data" / "PKD_PhoneMenu" / "SaveLoadApp" / "NUI_SaveAppMainScreen.json"
    src.parent.mkdir(parents=True)
    src.write_text(json.dumps({"childrens": [{"bindings": {"text": "Save?"}}]}), encoding="utf-8")
    out_dir = tmp_path / "out"

    apply_rpg_maker([TranslationResult(file=src, key="$.childrens[0].bindings.text", source="Save?", target="Lưu?")], out_dir)

    out_file = out_dir / "PKD_PhoneMenu" / "SaveLoadApp" / "NUI_SaveAppMainScreen.json"
    assert out_file.exists()
    assert not (out_dir / "NUI_SaveAppMainScreen.json").exists()
    data = json.loads(out_file.read_text(encoding="utf-8"))
    assert data["childrens"][0]["bindings"]["text"] == "Lưu?"


def test_apply_rpg_maker_skips_stale_key_and_applies_valid_rows(tmp_path):
    src = tmp_path / "data" / "Actors.json"
    src.parent.mkdir(parents=True)
    src.write_text(ACTORS_JSON, encoding="utf-8")
    out_dir = tmp_path / "out"

    results = [
        TranslationResult(file=src, key="$[1].missing", source="Old", target="Cũ"),
        TranslationResult(file=src, key="$[1].name", source="Harold", target="Ha-rôn"),
    ]

    apply_rpg_maker(results, out_dir)

    data = json.loads((out_dir / "Actors.json").read_text(encoding="utf-8"))
    assert data[1]["name"] == "Ha-rôn"
    assert "missing" not in data[1]


def test_apply_rpg_maker_raises_before_writing_when_all_rows_invalid(tmp_path):
    src = tmp_path / "data" / "Actors.json"
    src.parent.mkdir(parents=True)
    src.write_text(ACTORS_JSON, encoding="utf-8")
    out_dir = tmp_path / "out"

    results = [TranslationResult(file=src, key="$[99].name", source="Ghost", target="Ma")]

    with pytest.raises(ValueError, match="No valid translation rows"):
        apply_rpg_maker(results, out_dir)

    assert not (out_dir / "Actors.json").exists()


# ---------------------------------------------------------------------------
# MZ code 101 speaker name extraction
# ---------------------------------------------------------------------------

def test_extract_mz_speaker_name_from_code_101(tmp_path):
    map_data = json.dumps({
        "events": [
            None,
            {
                "id": 1,
                "pages": [
                    {
                        "list": [
                            {"code": 101, "parameters": ["", 0, 0, 2, "Theresia"]},
                            {"code": 401, "parameters": ["Hello there!"]},
                        ]
                    }
                ],
            },
        ],
    })
    _make_rpg_game(tmp_path, {"Map001.json": map_data})
    entries = extract_rpg_maker(tmp_path)
    sources = [e.source for e in entries]
    assert "Theresia" in sources
    assert "Hello there!" in sources
    speaker_entry = next(e for e in entries if e.source == "Theresia")
    assert speaker_entry.context == "rpg_maker_speaker_name"
    dialogue_entry = next(e for e in entries if e.source == "Hello there!")
    assert dialogue_entry.context == "rpg_maker_event_text"


def test_extract_mv_code_101_without_speaker_name(tmp_path):
    map_data = json.dumps({
        "events": [
            None,
            {
                "id": 1,
                "pages": [
                    {
                        "list": [
                            {"code": 101, "parameters": ["Actor1", 0, 0, 2]},
                            {"code": 401, "parameters": ["Hello!"]},
                        ]
                    }
                ],
            },
        ],
    })
    _make_rpg_game(tmp_path, {"Map001.json": map_data})
    entries = extract_rpg_maker(tmp_path)
    sources = [e.source for e in entries]
    assert "Hello!" in sources
    speaker_entries = [e for e in entries if e.context == "rpg_maker_speaker_name"]
    assert speaker_entries == []


def test_extract_mz_code_101_empty_speaker_not_extracted(tmp_path):
    map_data = json.dumps({
        "events": [
            None,
            {
                "id": 1,
                "pages": [
                    {
                        "list": [
                            {"code": 101, "parameters": ["", 0, 0, 2, ""]},
                            {"code": 401, "parameters": ["Hello!"]},
                        ]
                    }
                ],
            },
        ],
    })
    _make_rpg_game(tmp_path, {"Map001.json": map_data})
    entries = extract_rpg_maker(tmp_path)
    speaker_entries = [e for e in entries if e.context == "rpg_maker_speaker_name"]
    assert speaker_entries == []


# ---------------------------------------------------------------------------
# Event command 320/324/325 (Change Actor Name/Nickname/Profile)
# ---------------------------------------------------------------------------

def test_extract_change_actor_name_code_320(tmp_path):
    map_data = json.dumps({
        "events": [
            None,
            {
                "id": 1,
                "pages": [
                    {
                        "list": [
                            {"code": 320, "parameters": [1, "NewHeroName"]},
                            {"code": 0, "parameters": []},
                        ]
                    }
                ],
            },
        ],
    })
    _make_rpg_game(tmp_path, {"Map001.json": map_data})
    entries = extract_rpg_maker(tmp_path)
    sources = [e.source for e in entries]
    assert "NewHeroName" in sources
    name_entry = next(e for e in entries if e.source == "NewHeroName")
    assert name_entry.context == "rpg_maker_actors_name"
    assert name_entry.key.endswith("parameters[1]")


def test_extract_change_actor_nickname_code_324(tmp_path):
    map_data = json.dumps({
        "events": [
            None,
            {
                "id": 1,
                "pages": [
                    {
                        "list": [
                            {"code": 324, "parameters": [1, "The Brave"]},
                            {"code": 0, "parameters": []},
                        ]
                    }
                ],
            },
        ],
    })
    _make_rpg_game(tmp_path, {"Map001.json": map_data})
    entries = extract_rpg_maker(tmp_path)
    sources = [e.source for e in entries]
    assert "The Brave" in sources
    nick_entry = next(e for e in entries if e.source == "The Brave")
    assert nick_entry.context == "rpg_maker_actors_nickname"


def test_extract_change_actor_profile_code_325(tmp_path):
    map_data = json.dumps({
        "events": [
            None,
            {
                "id": 1,
                "pages": [
                    {
                        "list": [
                            {"code": 325, "parameters": [1, "A legendary warrior."]},
                            {"code": 0, "parameters": []},
                        ]
                    }
                ],
            },
        ],
    })
    _make_rpg_game(tmp_path, {"Map001.json": map_data})
    entries = extract_rpg_maker(tmp_path)
    sources = [e.source for e in entries]
    assert "A legendary warrior." in sources
    profile_entry = next(e for e in entries if e.source == "A legendary warrior.")
    assert profile_entry.context == "rpg_maker_actors_profile"


# ---------------------------------------------------------------------------
# States.json description field
# ---------------------------------------------------------------------------

STATES_JSON = json.dumps([
    None,
    {
        "id": 1,
        "name": "Poison",
        "description": "Takes damage each turn.",
        "message1": "%1 is poisoned!",
        "message2": "",
        "message3": "",
        "message4": "Poison was cured.",
    },
])


def test_extract_states_description(tmp_path):
    _make_rpg_game(tmp_path, {"States.json": STATES_JSON})
    entries = extract_rpg_maker(tmp_path)
    sources = [e.source for e in entries]
    assert "Poison" in sources
    assert "Takes damage each turn." in sources
    assert "%1 is poisoned!" in sources


def test_extract_mz_speaker_name_propagates_to_dialogue_context(tmp_path):
    map_data = json.dumps({
        "events": [
            None,
            {
                "id": 1,
                "pages": [
                    {
                        "list": [
                            {"code": 101, "parameters": ["", 0, 0, 2, "Theresia"]},
                            {"code": 401, "parameters": ["I will teach you."]},
                            {"code": 401, "parameters": ["Listen carefully."]},
                        ]
                    }
                ],
            },
        ],
    })
    _make_rpg_game(tmp_path, {"Map001.json": map_data})
    entries = extract_rpg_maker(tmp_path)
    dialogue_entries = [e for e in entries if e.context == "rpg_maker_event_text"]
    assert len(dialogue_entries) == 1
    merged_entry = dialogue_entries[0]
    assert "I will teach you." in merged_entry.source
    assert "Listen carefully." in merged_entry.source
    assert "[Theresia]" in merged_entry.context_text
    assert len(merged_entry.sub_keys) == 2


# ---------------------------------------------------------------------------
# _detect_json_indent
# ---------------------------------------------------------------------------

def test_detect_json_indent_minified():
    text = '{"name":"Harold","nickname":"The Sword"}'
    assert _detect_json_indent(text) is None


def test_detect_json_indent_2_spaces():
    text = '{\n  "name": "Harold",\n  "nickname": "The Sword"\n}'
    assert _detect_json_indent(text) == 2


def test_detect_json_indent_4_spaces():
    text = '[\n    null,\n    {\n        "name": "Harold"\n    }\n]'
    assert _detect_json_indent(text) == 4


def test_apply_rpg_maker_preserves_minified_format(tmp_path):
    minified_json = json.dumps([None, {"id": 1, "name": "Harold"}], ensure_ascii=False)
    src = tmp_path / "data" / "Actors.json"
    src.parent.mkdir(parents=True)
    src.write_text(minified_json, encoding="utf-8")
    out_dir = tmp_path / "out"

    results = [TranslationResult(file=src, key="$[1].name", source="Harold", target="Ha-rôn")]
    apply_rpg_maker(results, out_dir)

    out_text = (out_dir / "Actors.json").read_text(encoding="utf-8")
    assert "\n" not in out_text.strip()
    data = json.loads(out_text)
    assert data[1]["name"] == "Ha-rôn"


def test_apply_rpg_maker_rejects_rvdata2_entries(tmp_path):
    results = [
        TranslationResult(
            file=Path("Data/Actors.rvdata2"),
            key="$.events[1].pages[0].list[0].parameters[0]",
            source="Hello",
            target="Xin chao",
            context="rpg_maker_event_text",
        ),
    ]
    with pytest.raises(ValueError, match=r"\.rvdata2"):
        apply_rpg_maker(results, tmp_path / "out")


def test_apply_rpg_maker_preserves_indented_format(tmp_path):
    indented_json = json.dumps([None, {"id": 1, "name": "Harold"}], ensure_ascii=False, indent=2)
    src = tmp_path / "data" / "Actors.json"
    src.parent.mkdir(parents=True)
    src.write_text(indented_json, encoding="utf-8")
    out_dir = tmp_path / "out"

    results = [TranslationResult(file=src, key="$[1].name", source="Harold", target="Ha-rôn")]
    apply_rpg_maker(results, out_dir)

    out_text = (out_dir / "Actors.json").read_text(encoding="utf-8")
    assert "\n" in out_text
    lines = out_text.split("\n")
    indented_lines = [l for l in lines if l.startswith("  ") and not l.strip().startswith("]")]
    assert len(indented_lines) > 0
    data = json.loads(out_text)
    assert data[1]["name"] == "Ha-rôn"
