"""XUnity.AutoTranslator format extract/apply.

Translation files live under: Translation/{Lang}/Text/*.txt
- Each line is `original=translation` (translation may be empty for auto-generated stubs).
- Lines starting with `#` are scoping directives (skipped).
- Lines starting with `r:` or `sr:` are regex/splitter rules (preserved as-is, not translated).
- `_AutoGeneratedTranslations.txt` has lowest priority and is rewritten by the plugin.
- Files ending in `resizer.txt` use a different command syntax (skipped here).

We only translate plain `original=translation` entries. Regex/splicer rules and resizer
commands are left untouched — round-tripping them safely requires understanding game-
specific logic and the LLM should not rewrite them.
"""
from __future__ import annotations

from pathlib import Path
from typing import Iterator

from .models import TextEntry, TranslationResult

XUNITY_LANG_DIRS = ("Translation",)
SKIP_PREFIXES = ("#", "r:", "sr:")


def detect_xunity(game_dir: Path) -> Path | None:
    """Return the Translation directory if the game has XUnity AutoTranslator setup, else None."""
    for candidate in (game_dir / "Translation", game_dir / "BepInEx" / "Translation"):
        if candidate.is_dir():
            return candidate
    return None


def _is_translatable_line(line: str) -> bool:
    stripped = line.strip()
    if not stripped:
        return False
    if stripped.startswith(SKIP_PREFIXES):
        return False
    if "=" not in stripped:
        return False
    return True


def _parse_line(line: str) -> tuple[str, str] | None:
    if not _is_translatable_line(line):
        return None
    original, _, translation = line.rstrip("\r\n").partition("=")
    if not original:
        return None
    return original, translation


def _iter_xunity_text_files(translation_dir: Path) -> Iterator[Path]:
    """Yield all *.txt files under Translation/*/Text/ except resizer files."""
    for txt in translation_dir.rglob("*.txt"):
        if txt.name.endswith("resizer.txt"):
            continue
        yield txt


def extract_xunity(game_dir: Path) -> list[TextEntry]:
    """Read all XUnity translation files and return entries with empty/missing translations.

    Each entry's `key` is the original text itself (used as lookup key on apply).
    Already-translated entries (where translation != "") are still extracted so the
    LLM can review/improve them; downstream code can choose to skip those via memory.
    """
    translation_dir = detect_xunity(game_dir)
    if translation_dir is None:
        return []
    entries: list[TextEntry] = []
    seen: set[tuple[str, str]] = set()
    for file in _iter_xunity_text_files(translation_dir):
        try:
            text = file.read_text(encoding="utf-8-sig")
        except (OSError, UnicodeDecodeError):
            continue
        for line in text.splitlines():
            parsed = _parse_line(line)
            if parsed is None:
                continue
            original, _existing = parsed
            identity = (str(file), original)
            if identity in seen:
                continue
            seen.add(identity)
            entries.append(TextEntry(file=file, key=original, source=original, context="xunity_autotranslator"))
    return entries


def apply_xunity(results: list[TranslationResult], output_dir: Path) -> None:
    """Write translated entries back, grouped by source file, preserving non-translatable lines.

    Output structure mirrors input: results' `file` paths are used as relative anchors;
    we write each file under `output_dir` keeping its filename (no nested folders since
    XUAT flat-loads all .txt files in Translation/{Lang}/Text/).
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    by_file: dict[Path, dict[str, str]] = {}
    for r in results:
        by_file.setdefault(r.file, {})[r.source] = r.target

    for source_file, translations in by_file.items():
        try:
            original_text = source_file.read_text(encoding="utf-8-sig")
        except (OSError, UnicodeDecodeError):
            continue
        out_lines: list[str] = []
        for line in original_text.splitlines():
            parsed = _parse_line(line)
            if parsed is None:
                out_lines.append(line)
                continue
            original, _ = parsed
            new_target = translations.get(original)
            if new_target is None or not new_target.strip():
                out_lines.append(line)
            else:
                out_lines.append(f"{original}={new_target}")
        target = output_dir / source_file.name
        target.write_text("\n".join(out_lines) + "\n", encoding="utf-8")
