"""XUnity.AutoTranslator format extract/apply.

Translation files live under: Translation/{Lang}/Text/*.txt
- Each line is `original=translation` (translation may be empty for auto-generated stubs).
- Lines starting with `#` are scoping directives (skipped).
- Lines starting with `r:` or `sr:` are regex/splitter rules (preserved as-is, not translated).
- `_AutoGeneratedTranslations.txt` has lowest priority and is rewritten by the plugin.
- Files ending in `resizer.txt` use a different command syntax (skipped here).

We only translate plain `original=translation` entries. Regex/splicer rules and resizer
commands are left untouched — round-tripping them safely requires understanding game-
specific logic and the LLM should not rewrite them.
"""
from __future__ import annotations

from pathlib import Path
from typing import Iterator

from .models import TextEntry, TranslationResult

XUNITY_LANG_DIRS = ("Translation",)
SKIP_PREFIXES = ("#", "r:", "sr:")


def detect_xunity(game_dir: Path) -> Path | None:
    """Return the Translation directory if the game has XUnity AutoTranslator setup, else None."""
    for candidate in (game_dir / "Translation", game_dir / "BepInEx" / "Translation"):
        if candidate.is_dir():
            return candidate
    return None


def _is_translatable_line(line: str) -> bool:
    stripped = line.strip()
    if not stripped:
        return False
    if stripped.startswith(SKIP_PREFIXES):
        return False
    if "=" not in stripped:
        return False
    return True


def _parse_line(line: str) -> tuple[str, str] | None:
    if not _is_translatable_line(line):
        return None
    original, _, translation = line.rstrip("\r\n").partition("=")
    if not original:
        return None
    return original, translation


def _iter_xunity_text_files(translation_dir: Path) -> Iterator[Path]:
    """Yield Translation/{Lang}/Text/*.txt files except resizer files."""
    for text_dir in translation_dir.glob("*/Text"):
        if not text_dir.is_dir():
            continue
        for txt in text_dir.glob("*.txt"):
            if txt.name.endswith("resizer.txt"):
                continue
            yield txt


def extract_xunity(game_dir: Path, skip_translated: bool = True) -> list[TextEntry]:
    """Read all XUnity translation files and return entries that need translation.

    Each entry's `key` is the original text itself (used as lookup key on apply).
    By default (skip_translated=True), entries that already have a non-empty translation
    in the source .txt file are skipped — they don't need to be sent to the LLM again.
    Pass skip_translated=False to extract all entries regardless.
    """
    translation_dir = detect_xunity(game_dir)
    if translation_dir is None:
        return []
    entries: list[TextEntry] = []
    seen: set[tuple[str, str]] = set()
    for file in _iter_xunity_text_files(translation_dir):
        try:
            text = file.read_text(encoding="utf-8-sig")
        except (OSError, UnicodeDecodeError):
            continue
        for line in text.splitlines():
            parsed = _parse_line(line)
            if parsed is None:
                continue
            original, existing = parsed
            if skip_translated and existing.strip():
                continue
            identity = (str(file), original)
            if identity in seen:
                continue
            seen.add(identity)
            entries.append(TextEntry(file=file, key=original, source=original, context="xunity_autotranslator"))
    return entries


def apply_xunity(results: list[TranslationResult], output_dir: Path) -> None:
    """Write translated entries back, grouped by source file, preserving non-translatable lines.

    Output structure mirrors the input path below the detected Translation root. This avoids
    filename collisions when multiple language/Text folders contain the same filename.
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    by_file: dict[Path, dict[str, str]] = {}
    for r in results:
        by_file.setdefault(r.file, {})[r.source] = r.target

    for source_file, translations in by_file.items():
        try:
            original_text = source_file.read_text(encoding="utf-8-sig")
        except (OSError, UnicodeDecodeError):
            continue
        out_lines: list[str] = []
        for line in original_text.splitlines():
            parsed = _parse_line(line)
            if parsed is None:
                out_lines.append(line)
                continue
            original, _ = parsed
            new_target = translations.get(original)
            if new_target is None or not new_target.strip():
                out_lines.append(line)
            else:
                out_lines.append(f"{original}={new_target}")
        translation_root = next((parent for parent in source_file.parents if parent.name == "Translation"), None)
        relative = source_file.relative_to(translation_root) if translation_root is not None else Path(source_file.name)
        target = output_dir / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("\n".join(out_lines) + "\n", encoding="utf-8")
